# -*- coding: utf-8 -*-
"""Project 5: NN digit classification

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DG83NP0TNaZAxQUcfdyyzqmKoRKXyP0k
"""

!wget -q https://github.com/mnielsen/neural-networks-and-deep-learning/raw/master/data/mnist.pkl.gz -O mnist.pkl.gz

import numpy as np
import random
import pickle
import gzip


class Network(object):

  def __init__(self, sizes): # sizes gives the size of the neural net, we define it at the end of this code
        self.num_layers = len(sizes) # this stores how many layers the network has, in this case 3
        self.sizes = sizes # this stores the actual list of sizes of the network
        self.biases = [np.random.randn(y, 1) for y in sizes[1:]] # (y,1) indicates it is a column vector and the rows(y) have been randomly generated, 1: indicates input layer not given a bias
        self.weights = [np.random.randn(y, x)
                        for x, y in zip(sizes[:-1], sizes[1:])]

# weight matrices live BETWEEN layers, so n layers need n-1 of them.
# sizes[:-1] and sizes[1:] are offset the sizes list then zip
# matches (sender, receiver) pairwise: (784,30), (30,10).
# each matrix is (receiver, sender) so that w dot a works without a transpose.

  def sigmoid(self, z):
        return 1.0/(1.0+np.exp(-z)) # function needed to take z= w.a + b into a an output between 0 and 1

  def sigmoid_prime(self, z):
        return self.sigmoid(z)*(1-self.sigmoid(z)) # basic calculus- derivative of sigmoid function is of this form after some manipulation

  def feedforward(self, a): # a is intially the 784 pixel values in a column vector --> 30 value vector --> 10 value ouput vector

        for b, w in zip(self.biases, self.weights): # zip simply pairs weight[0] to biases[0] etc... loop runs twice here for [0] and [1]
            a = self.sigmoid(np.dot(w, a)+b)
        return a


  def SGD(self, training_data, epochs, mini_batch_size, eta, # stochastic gradient descent- minimises the cost function stepwise via small mini-batches
            test_data=None):

            if test_data: n_test = len(test_data)

            n = len(training_data)

            for j in range(epochs): # for as many epochs (full pass over the n data points) as we set

              random.shuffle(training_data) # makes the mini-batches completely random
              mini_batches = [
                training_data[k:k+mini_batch_size]
                  for k in range(0, n, mini_batch_size)] # n is the number of total samples, mini_batch_size determines into what slices the batch is cut

              for mini_batch in mini_batches:
                self.update_mini_batch(mini_batch, eta) # eta is the training rate as set at the end of code

              if test_data:
                    print ("Epoch {0}: {1} / {2}".format(
                    j, self.evaluate(test_data), n_test)) # this runs once every epoch and evaluates the network's predictions for 10,000 test images
              else:
                    print ("Epoch {0} complete".format(j))

  def update_mini_batch(self, mini_batch, eta):

        nabla_b = [np.zeros(b.shape) for b in self.biases]  # makes zero vectors in shape of biases
        nabla_w = [np.zeros(w.shape) for w in self.weights] # makes zero matrices in shape of weights

        # zeros used intially so that when first example's gradient added the nabla_b/w purely represent the gradient of that first example

        for x, y in mini_batch:

            delta_nabla_b, delta_nabla_w = self.backprop(x, y) # returns gradient for one example

            nabla_b = [nb+dnb for nb, dnb in zip(nabla_b, delta_nabla_b)] # the zipping allows elementwise addition of the new gradient to old gradient

            nabla_w = [nw+dnw for nw, dnw in zip(nabla_w, delta_nabla_w)] # same thing happens here for the weights



        self.weights = [w-(eta/len(mini_batch))*nw
                        for w, nw in zip(self.weights, nabla_w)]

        self.biases = [b-(eta/len(mini_batch))*nb
                       for b, nb in zip(self.biases, nabla_b)]

        # formulas derived in workbook, they apply changes to the bias and weight depending on the gradient

  def backprop(self, x, y):

        nabla_b = [np.zeros(b.shape) for b in self.biases]
        nabla_w = [np.zeros(w.shape) for w in self.weights]

        activation = x
        activations = [x] # lists activations
        zs = []
        for b, w in zip(self.biases, self.weights): # for matching pairs of weights and biases
            z = np.dot(w, activation)+b # operation to track from one neuron to the next
            zs.append(z) # add these neuron values to a list
            activation = self.sigmoid(z) # convert neuron values to sigmoidal 0-1 values
            activations.append(activation) # add activation values to a list

        # this is the forward-feed section

        delta = self.cost_derivative(activations[-1], y) * \
            self.sigmoid_prime(zs[-1]) # -1 index as we want the final thing appended to the list because z and a have different list lengths

        # delta is dc/dz = dc/da * da/dz, that is what this line is saying, it is the output layer error

        nabla_b[-1] = delta
        nabla_w[-1] = np.dot(delta, activations[-2].transpose()) # -2 here as the formula requires activations from layer l-1



        for l in range(2, self.num_layers):
            z = zs[-l]
            sp = self.sigmoid_prime(z)
            delta = np.dot(self.weights[-l+1].transpose(), delta) * sp # equation derived in workbook
            nabla_b[-l] = delta
            nabla_w[-l] = np.dot(delta, activations[-l-1].transpose())

        return (nabla_b, nabla_w)

  def evaluate(self, test_data):

        test_results = [(np.argmax(self.feedforward(x)), y)
                        for (x, y) in test_data]
        return sum(int(x == y) for (x, y) in test_results)

  def cost_derivative(self, output_activations, y):

        return (output_activations-y) # this quadratic cost method gives the problem that the network learns most from small errors, large errors are in saturated neurons and have small effect


def load_data():

    f = gzip.open('mnist.pkl.gz', 'rb')
    training_data, validation_data, test_data = pickle.load(f, encoding='latin1')
    f.close()
    return (training_data, validation_data, test_data)



def load_data_wrapper():
    tr_d, va_d, te_d = load_data()
    training_inputs = [np.reshape(x, (784, 1)) for x in tr_d[0]]
    training_results = [vectorized_result(y) for y in tr_d[1]]
    training_data = list(zip(training_inputs, training_results))
    validation_inputs = [np.reshape(x, (784, 1)) for x in va_d[0]]
    validation_data = list(zip(validation_inputs, va_d[1]))
    test_inputs = [np.reshape(x, (784, 1)) for x in te_d[0]]
    test_data = list(zip(test_inputs, te_d[1]))
    return (training_data, validation_data, test_data)

def vectorized_result(j):

    e = np.zeros((10, 1))
    e[j] = 1.0
    return e

training_data, validation_data, test_data = load_data_wrapper()
net = Network([784, 30, 10]) # (input,hidden layer,output)
net.SGD(training_data, 10, 10, 2, test_data=test_data) # (number of epochs,mini-batch size,eta- learning rate)