# -*- coding: utf-8 -*-
"""Project 7: CNN digit classifier, Momentum implemented, CNN PyTorch

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19NXKoBH2APTVn36yd6ZGKQ5_rPivUCgu
"""

!wget -q https://github.com/mnielsen/neural-networks-and-deep-learning/raw/master/data/mnist.pkl.gz -O mnist.pkl.gz

import torch, torch.nn as nn, gzip, pickle

f = gzip.open('mnist.pkl.gz','rb')
tr_d, va_d, te_d = pickle.load(f, encoding='latin1'); f.close()

# details on loading the data

Xtr = torch.tensor(tr_d[0], dtype=torch.float32) # stores numbers with 32 bits, faster than 64, better here as gradients have noise
ytr = torch.tensor(tr_d[1], dtype=torch.long)
Xte = torch.tensor(te_d[0], dtype=torch.float32)
yte = torch.tensor(te_d[1], dtype=torch.long) # 'long' as these are labels- the integer classes

# tensors can track operations so can run the gradient backwards as needed for backprop

model = nn.Sequential( # model(X) calls the forwardfeed pass

    nn.Linear(784, 30), # stores and intitialises all weights and biases
    nn.Sigmoid(), # applies the sigmoid function
    nn.Linear(30, 10), # outputs logits
)

loss_fn = nn.CrossEntropyLoss() # final line remains linear, this applies softmax to the final layer of data within loss and then uses log-likelihood cost function
opt = torch.optim.SGD(model.parameters(), lr=0.25, momentum=0.5, weight_decay=1e-4) # this line stores references to parameters and allocates velocity buffers
# lr = learning rate, momentum = mu, weight decay = lambda as a part of L2 regularization

n = len(Xtr)
for epoch in range(30):
    perm = torch.randperm(n) # creates a random permutation of the indices
    for k in range(0, n, 10):
        idx = perm[k:k+10] # this slices the data into mini-batches
        opt.zero_grad() # this acts as the reset to the gradient between mini-batches
        loss = loss_fn(model(Xtr[idx]), ytr[idx]) # this is the forward pass, applies softmax to logits and averages over 10 samples
        loss.backward() # this is where the backpropagation happens; replaces our entire from scratch method
        opt.step() # applies the weight decay, learning rate, and velocity to old weights and biases to find new ones
    with torch.no_grad():
        acc = (model(Xte).argmax(1) == yte).sum().item() # this evaluates how many of the final layers in the sample correctly chose the class and sums them up to show as a fraction
    print(f"epoch {epoch}: {acc} / 10000")

import torch, torch.nn as nn, gzip, pickle

f = gzip.open('mnist.pkl.gz','rb')
tr_d, va_d, te_d = pickle.load(f, encoding='latin1'); f.close()

# details on loading the data

Xtr = torch.tensor(tr_d[0], dtype=torch.float32).reshape(-1,1,28,28) # (batch, channels(colour), height, width), the -1 tells pytorch to infer the batch number from the elements present in the tensor
ytr = torch.tensor(tr_d[1], dtype=torch.long)
Xte = torch.tensor(te_d[0], dtype=torch.float32).reshape(-1,1,28,28)
yte = torch.tensor(te_d[1], dtype=torch.long) # 'long' as these are labels- the integer classes

# tensors can track operations so can run the gradient backwards as needed for backprop


model = nn.Sequential(
    nn.Conv2d(1, 20, 5), nn.ReLU(), nn.MaxPool2d(2), # one input channel i.e. all pixels are grey, 20 feature maps formed of 5x5 squares, using ReLu and 2x2 pooling
    nn.Conv2d(20, 40, 5), nn.ReLU(), nn.MaxPool2d(2), # this is the second convnet layer, it takes the twenty feature maps and turns them into fourty again formed of 5x5
    nn.Flatten(), # this then takes the outcomes of the pooling and flattens it into a single vector
    nn.Linear(640, 100), nn.ReLU(), # takes 640 element vector output of the convnet layers and has a fully connected layer down to 100 neurons
    nn.Linear(100, 10), # from 100 down to 10 output neurons as our design requires
)



loss_fn = nn.CrossEntropyLoss() # final line remains linear, this applies softmax to the final layer of data within loss and then uses log-likelihood cost function
opt = torch.optim.SGD(model.parameters(), lr=0.01, momentum=0.9, weight_decay=1e-4) # this line stores references to parameters and allocates velocity buffers
# lr = learning rate, momentum = mu, weight decay = lambda as a part of L2 regularization

n = len(Xtr)
for epoch in range(30):
    perm = torch.randperm(n) # creates a random permutation of the indices
    for k in range(0, n, 10):
        idx = perm[k:k+10] # this slices the data into mini-batches
        opt.zero_grad() # this acts as the reset to the gradient between mini-batches
        loss = loss_fn(model(Xtr[idx]), ytr[idx]) # this is the forward pass, applies softmax to logits and averages over 10 samples
        loss.backward() # this is where the backpropagation happens; replaces our entire from scratch method
        opt.step() # applies the weight decay, learning rate, and velocity to old weights and biases to find new ones
    with torch.no_grad():
        acc = (model(Xte).argmax(1) == yte).sum().item() # this evaluates how many of the final layers in the sample correctly chose the class and sums them up to show as a fraction
    print(f"epoch {epoch}: {acc} / 10000")